/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package farmacia.farmaciaofc.gui;

import farmacia.farmaciaofc.dao.UsuarioDAO;
import farmacia.farmaciaofc.dto.FuncionarioDTO;
import farmacia.farmaciaofc.dto.UsuarioDTO;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author talit
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ACESSARCLIENTES = new javax.swing.JToggleButton();
        ACESSARFUNCIONARIOS = new javax.swing.JToggleButton();
        CLIENTES = new javax.swing.JLabel();
        FUNCIONARIOS = new javax.swing.JLabel();
        COSMETICOS = new javax.swing.JLabel();
        MEDICAMENTOS = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuariodois = new javax.swing.JTextField();
        txtSenhadois = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUsuarioum = new javax.swing.JTextField();
        txtSenhaum = new javax.swing.JPasswordField();
        txtUsuariotres = new javax.swing.JTextField();
        txtSenhatres = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ACESSARCOSMETICOS = new javax.swing.JButton();
        ACESSARMEDICAMENTOS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setText("FARMÁCIAS GASA");

        ACESSARCLIENTES.setBackground(new java.awt.Color(255, 204, 204));
        ACESSARCLIENTES.setText("ACESSAR");
        ACESSARCLIENTES.setActionCommand("ACESSARCLIENTES");
        ACESSARCLIENTES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACESSARCLIENTESActionPerformed(evt);
            }
        });

        ACESSARFUNCIONARIOS.setBackground(new java.awt.Color(255, 204, 204));
        ACESSARFUNCIONARIOS.setText("ACESSAR");
        ACESSARFUNCIONARIOS.setActionCommand("ACESSARFUNCIONARIOS");
        ACESSARFUNCIONARIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACESSARFUNCIONARIOSActionPerformed(evt);
            }
        });

        CLIENTES.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        CLIENTES.setText("CLIENTES");

        FUNCIONARIOS.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        FUNCIONARIOS.setText("FUNCIONÁRIOS");

        COSMETICOS.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        COSMETICOS.setText("COSMÉTICOS");

        MEDICAMENTOS.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        MEDICAMENTOS.setText("MEDICAMENTOS");

        jLabel2.setText("USUÁRIO:");

        jLabel3.setText("SENHA:");

        jLabel4.setText("USUÁRIO:");

        jLabel5.setText("SENHA:");

        jLabel6.setText("USUÁRIO:");

        jLabel7.setText("SENHA:");

        jLabel8.setText("USUÁRIO:");

        jLabel9.setText("SENHA:");

        ACESSARCOSMETICOS.setBackground(new java.awt.Color(255, 204, 204));
        ACESSARCOSMETICOS.setText("ACESSAR");
        ACESSARCOSMETICOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACESSARCOSMETICOSActionPerformed(evt);
            }
        });

        ACESSARMEDICAMENTOS.setBackground(new java.awt.Color(255, 204, 204));
        ACESSARMEDICAMENTOS.setText("ACESSAR");
        ACESSARMEDICAMENTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACESSARMEDICAMENTOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FUNCIONARIOS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MEDICAMENTOS))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(ACESSARCLIENTES)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(93, 93, 93))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSenhadois, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsuariodois, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ACESSARFUNCIONARIOS)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CLIENTES)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(72, 72, 72)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(109, 109, 109)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(COSMETICOS)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ACESSARCOSMETICOS)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtUsuarioum)
                                                        .addComponent(txtSenhaum, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel9))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ACESSARMEDICAMENTOS)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtUsuariotres)
                                                        .addComponent(txtSenhatres, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))))))))
                        .addContainerGap(9, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CLIENTES)
                            .addComponent(COSMETICOS))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtUsuarioum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtSenhaum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACESSARCLIENTES)
                    .addComponent(ACESSARCOSMETICOS))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FUNCIONARIOS)
                    .addComponent(MEDICAMENTOS))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuariodois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuariotres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSenhadois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenhatres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACESSARFUNCIONARIOS)
                    .addComponent(ACESSARMEDICAMENTOS))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ACESSARFUNCIONARIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACESSARFUNCIONARIOSActionPerformed
        // TODO add your handling code here:
        logar();
        
    }//GEN-LAST:event_ACESSARFUNCIONARIOSActionPerformed

    private void ACESSARCLIENTESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACESSARCLIENTESActionPerformed
        // TODO add your handling code here:
        logar1();
    }//GEN-LAST:event_ACESSARCLIENTESActionPerformed

    private void ACESSARCOSMETICOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACESSARCOSMETICOSActionPerformed
        // TODO add your handling code here:
        logar2();
    }//GEN-LAST:event_ACESSARCOSMETICOSActionPerformed

    private void ACESSARMEDICAMENTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACESSARMEDICAMENTOSActionPerformed
        // TODO add your handling code here:
        logar3();
        
    }//GEN-LAST:event_ACESSARMEDICAMENTOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ACESSARCLIENTES;
    private javax.swing.JButton ACESSARCOSMETICOS;
    private javax.swing.JToggleButton ACESSARFUNCIONARIOS;
    private javax.swing.JButton ACESSARMEDICAMENTOS;
    private javax.swing.JLabel CLIENTES;
    private javax.swing.JLabel COSMETICOS;
    private javax.swing.JLabel FUNCIONARIOS;
    private javax.swing.JLabel MEDICAMENTOS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenhadois;
    private javax.swing.JPasswordField txtSenhatres;
    private javax.swing.JPasswordField txtSenhaum;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuariodois;
    private javax.swing.JTextField txtUsuariotres;
    private javax.swing.JTextField txtUsuarioum;
    // End of variables declaration//GEN-END:variables
public void logar1 () {
        //String sql = "select * from usuarios where email=? and senha=?";
        try {

            String user = txtUsuario.getText();
            String password = new String(txtSenha.getPassword());

            UsuarioDTO objUsuario = new UsuarioDTO(WIDTH, user, password);
            objUsuario.setUsuario(user);
            objUsuario.setSenha(password);

            UsuarioDAO usuario = new UsuarioDAO();
            ResultSet rsUserDao = usuario.autenticacaoUsuario(objUsuario);

            if (rsUserDao.next()) {
                TelaCliente produtoTela = new TelaCliente ();
                produtoTela.setVisible(true);
                dispose(); // Fecha a tela anterior
            } else {
                JOptionPane.showMessageDialog(null, "Dados Inválidos");
                limparCampos();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    // Função para limpar os campos JTextField
    public void limparCampos1() {
        txtUsuario.setText(null);
        txtSenha.setText(null);
        txtUsuario.requestFocus();
    }
    
    public void logar () {
        //String sql = "select * from usuarios where email=? and senha=?";
        try {

            String user = txtUsuariodois.getText();
            String password = new String(txtSenhadois.getPassword());

            UsuarioDTO objUsuario = new UsuarioDTO(WIDTH, user, password);
            objUsuario.setUsuario(user);
            objUsuario.setSenha(password);

            UsuarioDAO usuario = new UsuarioDAO();
            ResultSet rsUserDao = usuario.autenticacaoUsuario(objUsuario);

            if (rsUserDao.next()) {
                TelaFuncionario produtoTela = new TelaFuncionario();
                produtoTela.setVisible(true);
                dispose(); // Fecha a tela anterior
            } else {
                JOptionPane.showMessageDialog(null, "Dados Inválidos");
                limparCampos();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    // Função para limpar os campos JTextField
    public void limparCampos() {
        txtUsuariodois.setText(null);
        txtSenhadois.setText(null);
        txtUsuariodois.requestFocus();
    }
    
    public void logar2 () {
        //String sql = "select * from usuarios where email=? and senha=?";
        try {

            String user = txtUsuarioum.getText();
            String password = new String(txtSenhaum.getPassword());

            UsuarioDTO objUsuario = new UsuarioDTO(WIDTH, user, password);
            objUsuario.setUsuario(user);
            objUsuario.setSenha(password);

            UsuarioDAO usuario = new UsuarioDAO();
            ResultSet rsUserDao = usuario.autenticacaoUsuario(objUsuario);

            if (rsUserDao.next()) {
                TelaCosmeticos produtoTela = new TelaCosmeticos ();
                produtoTela.setVisible(true);
                dispose(); // Fecha a tela anterior
            } else {
                JOptionPane.showMessageDialog(null, "Dados Inválidos");
                limparCampos();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    // Função para limpar os campos JTextField
    public void limparCampos2() {
        txtUsuarioum.setText(null);
        txtSenhaum.setText(null);
        txtUsuarioum.requestFocus();
    }
    
    
    public void logar3 () {
        //String sql = "select * from usuarios where email=? and senha=?";
        try {

            String user = txtUsuariotres.getText();
            String password = new String(txtSenhatres.getPassword());

            UsuarioDTO objUsuario = new UsuarioDTO(WIDTH, user, password);
            objUsuario.setUsuario(user);
            objUsuario.setSenha(password);

            UsuarioDAO usuario = new UsuarioDAO();
            ResultSet rsUserDao = usuario.autenticacaoUsuario(objUsuario);

            if (rsUserDao.next()) {
                TelaMedicamentos produtoTela = new TelaMedicamentos ();
                produtoTela.setVisible(true);
                dispose(); // Fecha a tela anterior
            } else {
                JOptionPane.showMessageDialog(null, "Dados Inválidos");
                limparCampos();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    // Função para limpar os campos JTextField
    public void limparCampos3() {
        txtUsuariotres.setText(null);
        txtSenhatres.setText(null);
        txtUsuariotres.requestFocus();
    }
    
}
